### ISSUE TITLE
TplinkC1200Router' object has no attribute '_login_referer

### ISSUE THREAD

**Issue by rkononov** [AlexandrErohin/home-assistant-tplink-router#42]
**Describe the bug**
After the most recent update the router (Archer C1200) started failing with the following message 
"'TplinkC1200Router' object has no attribute '_login_referer'"

I tried to remove the integration and set this up again but keep getting the same message (listed above).
The integration worked perfectly for a couple of months before. (router has the same firmware so nothing was changed that side)

**Logs**

Logger: custom_components.tplink_router.config_flow
Source: custom_components/tplink_router/config_flow.py:48
integration: TP-Link Router ([documentation](https://github.com/AlexandrErohin/home-assistant-tplink-router), [issues](https://github.com/AlexandrErohin/home-assistant-tplink-router/issues))
First occurred: 10:58:54 PM (5 occurrences)
Last logged: 11:03:59 PM

TplinkRouter Integration Exception - 'TplinkC1200Router' object has no attribute '_login_referer'
**Additional Information (please complete the following information)**
 - Router Hardware Version: Archer C2300 v1.0
 - Router Firmware Version: 2.0.7 Build 20230906 Rel. 34754(4555/4445)
 - Home Assistant Version: 2024.3.1
 - TP-Link Router Integration Component Version: the latest one (I cannot even install it now since it cannot be configured)

**Comment by AlexandrErohin** [comment]
Hi.
It was a large client update to support Deco Mesh routers.
I have fixed the bag.
Please try v1.11.1 and let me know

**Comment by rkononov** [comment]
Hey @AlexandrErohin thank you for your prompt response, seems like still broken but in a different manner, here are the logs:

Logger: homeassistant.config_entries
Source: config_entries.py:504
First occurred: 7:56:35 PM (1 occurrences)
Last logged: 7:56:35 PM

```
Error setting up entry http://192.168.1.1 for tplink_router
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 504, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_router/__init__.py", line 47, in async_setup_entry
    firmware, status = await hass.async_add_executor_job(TPLinkRouterCoordinator.request, client, callback)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tplink_router/coordinator.py", line 56, in request
    data = callback()
           ^^^^^^^^^^
  File "/config/custom_components/tplink_router/__init__.py", line 42, in callback
    firm = client.get_firmware()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tplinkrouterc6u/client.py", line 295, in get_firmware
    data = self.request(self._url_firmware, 'operation=read')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tplinkrouterc6u/client.py", line 109, in request
    raise ClientError(error)
tplinkrouterc6u.exception.ClientError: TplinkRouter - TplinkC1200Router - An unknown response - Router didn't respond with JSON; Request admin/firmware?form=upgrade&operation=read - Response {'errorcode': 'no such callback', 'success': False}
```

**Comment by AlexandrErohin** [comment]
That's better.
I have made a fix.
Please try v1.11.2 and let me know

P.S. Unfortunately, I dont have this router so I cannot test by my own :(

**Comment by rkononov** [comment]
@AlexandrErohin thank you so much, the issue was fixed!

**Comment by AlexandrErohin** [comment]
@rkononov Dont forget please to give a star to the repo :)
